title: Patterns
author: Cornelis G. A. Kolbach
baseurl: http://patterns.cornae.com
domain: patterns.cornae.com
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
  load_paths:
    - "_sass"
    - "src/bower_components/patternslib/"
    - "src/bower_components/patternslib/_sass"
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
