title: Patterns
author: Cornelis G. A. Kolbach
summary: Patternslib is a free toolkit that aims to bring web design and development closer together.
# bundle_url and patternslib_version are automatically set by the Makefile target `make update-patternslib`.
bundle_url: https://cdn.jsdelivr.net/npm/@patternslib/patternslib@9.10.2/dist/bundle.min.js
patternslib_version: 9.10.2
baseurl: /
domain: www.patternslib.com
media: /media
markdown: kramdown
permalink: /:title
port: 4004
collections_dir: content
collections:
  demos:
    output: true
  download:
    output: true
  showcases:
    output: true
  documentation:
    output: true
sass:
  style: :compressed
  load_paths:
    - "_sass"
exclude:
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - patternslib/src/bower_components
  - patternslib/node_modules
  - Makefile
  - README.md
  - bower.json
  - main.js
  - bundle-config.js
  - src/
  - stamp-bower
  - stamp-npm
  - stamp-bundler
