title: Patterns
author: Cornelis G. A. Kolbach
baseurl: /
domain: www.patternslib.com
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
  load_paths:
    - "_sass"
    - "patternslib"
    - "patternslib/_sass"
placeholder-1x1: 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=='
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - patternslib/src/bower_components
  - patternslib/node_modules
  - Makefile
  - README.md
  - bower.json
  - main.js
  - bundle-config.js
  - src/
  - stamp-bower
  - stamp-npm
  - stamp-bundler