title: Patterns
author: Cornelis G. A. Kolbach
baseurl: /
domain: patterns.cornae.com
media: /media
markdown: kramdown
permalink: /:title
sass:
  style: :compressed
  load_paths:
    - "_sass"
    - "patternslib"
    - "patternslib/_sass"
exclude: 
  - Gemfile
  - Gemfile.lock
  - config.codekit
  - config.rb
  - node_modules
  - patternslib/src/bower_components
patterns:
  - version: 1.1.1
  - components:
    - modal
    - avatar
    - equaliser
    - grid
  - basics: 
    - reset
    - clear-fix
